### PR TITLE
[3rd Week] Updated Attraction Page with (1) RWD, (2) Fetching Individ…

### PR DESCRIPTION
**Pull request by skwongman**
Dear Peng Peng,

For the 3rd week WeHelp assignment, please refer to my coding and following URLs for your checking before I merge into the main branch.

http://52.205.132.168:3000/
http://52.205.132.168:3000/attraction/10

Please feel free to let me know if you have any comment. Thank you so much.

Best Regards,
KM Siu (蕭廣文)

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We don't need to add background image for date input, just use default style.
2. Separator line should be only 1px height.

**Comment by skwongman** [comment]
> 1. We don't need to add background image for date input, just use default style.
> 
>     2. Separator line should be only 1px height.

Dear Peng Peng,

I have already removed calendar icon and updated the height of separate line as per your comment. For your review again, please. Thank you.

http://52.205.132.168:3000/attraction/10

Best Regards,
KM Siu (蕭廣文)

**Review by cwpeng — CHANGES_REQUESTED** [review]
Your separator line has 3px height (1px height + 2px border) actually.

**Comment by skwongman** [comment]
> Your separator line has 3px height (1px height + 2px border) actually.

Dear Peng Peng,

I have updated the height of separate line as per your comment. For your review again, please. Thank you.

http://52.205.132.168:3000/attraction/10

Best Regards,
KM Siu (蕭廣文)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
